---
title: "Text Analysis for Country Information"
author: "Fang Ren"
format:
  html:
    toc: true
    toc-location: left
    self-contained: true
jupyter: python3
---

## Step 1: Getting Country Data

Your source of text will come from britannica.com. There are a few pages that will have lists of countries, but you can use this one as a starting place: https://www.britannica.com/topic/list-of-countries-1993160. For each country, pull information about **Resources** from the **Economy** section of the page (when available). Here is something that will most likely be useful to you as you start looking for this information: `[a['href'] for a in soup.find_all("a", string=re.compile("Resources"))]`. You might find that additional pieces of information sneek in as you scrape the data, and that is fine. 

You will also want to make use of the random sleep idea that we discussed in class! 

Remember that this is a step by step process (i.e., the countries page will lead you to the country page, which will lead you to the Economy section). Each step will produce a link that take you to the next step.

```{python}
import requests
from bs4 import BeautifulSoup
import time
import numpy as np
import pandas as pd
import re

url = "https://www.britannica.com/topic/list-of-countries-1993160"
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

country_links = []
for a in soup.find_all("a"):
    try:
        href = a["href"]
        if "/place/" in a["href"]:
            country_links.append(href)
    except:
        continue

data = []

for country_url in country_links:
    time.sleep(np.random.uniform(1, 3))
    response = requests.get(country_url)
    country_soup = BeautifulSoup(response.content, "html.parser")

    economy_links = []
    for a in country_soup.find_all("a"):
        try:
            href = a["href"]
            if "/Economy" in a["href"]:
                economy_links.append("https://www.britannica.com" + href)
        except:
            continue

    if not economy_links:
        continue

    time.sleep(np.random.uniform(1, 3))
    econ_response = requests.get(economy_links[0])
    econ_soup = BeautifulSoup(econ_response.content, "html.parser")

    resource_links = ["https://www.britannica.com" + a['href'] for a in econ_soup.find_all("a", string=re.compile("Resources"))]

    if not resource_links:
        continue

    time.sleep(np.random.uniform(1, 3))
    resource_response = requests.get(resource_links[0])
    resource_soup = BeautifulSoup(resource_response.content, "html.parser")
    resources_text = " ".join(p.text for p in resource_soup.find_all("p"))

    data.append({"country": country_url, "resources": resources_text})

df = pd.DataFrame(data)
print(df)

```


## Step 2: Sentiment Analysis

Perform any two types of sentiment analysis on your scraped text -- it doesn't matter which two you choose. Before performing your analysis, articulate what you would expect to find from these analyses. 

Visually compare your two sentiment scores and discuss if they are different than what you had expected.

```{python}
#VADER
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

vader = SentimentIntensityAnalyzer()

result = []
for text in df['resources']:
    score = vader.polarity_scores(text).get('compound')
    result.append(score)

df['vader'] = result
print(df[['country', 'vader']])
```

python3 -m textblob.download_corpora
```{python}
#NB
import textblob
from textblob.sentiments import NaiveBayesAnalyzer
#statement = "I dislike code, but I really love money."
#output = textblob.TextBlob(statementanalyzer=NaiveBayesAnalyzer()).sentiment
output= []
for text in df['resources']:
    score = textblob.TextBlob(text, analyzer=NaiveBayesAnalyzer()).sentiment
    output.append(score)

df['NB'] = output
print(df[['country', 'NB']])

nb_scores = []

for text in df['resources']:
    sentiment = textblob.TextBlob(text, analyzer=NaiveBayesAnalyzer()).sentiment
    score = sentiment.p_pos - sentiment.p_neg
    nb_scores.append(score)

df['nb_score'] = nb_scores
print(df[['country', 'nb_score']])
```

```{python}
#visualization
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
plt.title('VADER vs Naive Bayes')
plt.scatter(range(len(df)), df['vader'], color='steelblue', alpha=0.7, label='VADER')
plt.scatter(range(len(df)), df['nb_score'], color='orange', alpha=0.7, label='NaiveBayes')
plt.legend()
plt.show()
```

Discussion：
Before running the sentiment analysis, I expected the country descriptions from Britannica to be purely objective. Naturally, I thought both VADER and Naive Bayes would return scores close to zero. However the actual results showed a clear positive bias across the board. Naive Bayes was particularly extreme while VADER showed a bit more variety, it still leaned heavily toward the positive side. In conclusion, it is clear that these 2 sentiment models really struggle with factual writing.

## Step 3: Topic Modeling

Clean and prepare your text, and then perform either form of topic modeling discussed in class (LDA or BERT). What are the main themes that you find in the topics that you generate?
```{python}
#LDA
from joblib import load, dump
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf

import pandas as pd
import pprint as pprint

import requests

from sklearn.decomposition import LatentDirichletAllocation 
from sklearn.feature_extraction.text import CountVectorizer

stopwords = requests.get('https://raw.githubusercontent.com/stopwords-iso/stopwords-en/refs/heads/master/stopwords-en.txt')

stopwords = stopwords.text.split('\n')

stopword_pattern = r'\b(?:{})\b'.format('|'.join(stopwords))

df['resources_clean'] = df['resources'].str.lower()
df['resources_clean'] = df['resources_clean'].str.replace(stopword_pattern, '', regex=True)
df['resources_clean'] = df['resources_clean'].str.replace(r"[\(\).,?!;:'-]", '', regex=True)
df['resources_clean'] = df['resources_clean'].str.replace(' +', ' ', regex=True)

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['resources_clean'])
vocab = vectorizer.get_feature_names_out()

model = LatentDirichletAllocation(
    n_components=5,
    random_state=1
)
model.fit(X)

topic_word  = model.components_   
n_top_words = 10   

for i, topic_dist in enumerate(topic_word):
    topic_words = np.array(vocab)[np.argsort(topic_dist)][:-n_top_words:-1]
    print('Topic {}: {}'.format(i, ' '.join(topic_words)))

doc_topic = model.transform(X)

df['top_topic'] = np.argmax(doc_topic, axis=1)
df['top_prob'] = np.max(doc_topic, axis=1)

print(df[['country', 'top_topic', 'top_prob']])


```

The LDA model grouped the country resource descriptions into five topics, mainly reflecting differences in economic structure and resource composition.
The topics focus on energy resources such as oil, natural gas, and coal, while others emphasize export-oriented and government-led economies. Additional themes capture economic growth and development in Asian countries as well as industrial structure and natural resource reserves.
