---
title: "The Command Line Interface"
format:
  html:
    toc: true
    toc-location: left
    self-contained: true
---

## Connecting to the CRC

To connect to the CRC, you will need to use SSH. If you are using a Mac or Linux machine, you can just open up your terminal and type the following:

```
ssh netid@crcfe01.crc.nd.edu
```

If you are using Windows, you'll need to use an SSH client. The CRC recommends using MobaXterm, which you can download [here](https://mobaxterm.mobatek.net/download-home-edition.html). Once you have MobaXterm installed, open it up and click on `Session` in the top left. From there, select `SSH`. 

In the `Remote host` box, type in `crcfe01.crc.nd.edu`. In the `Specify username` box, type in your NetID. Once that is done, click `OK`. After authentication, you should now be connected to the CRC!

## Doing Work on the CRC

If you are using a Windows machine and have Git installed (you should have Git installed), you can do the following:

```
"C:\Program Files\Git\usr\bin\vim.exe" app.py
```

On a Mac, you can just do this:

```
vim app.py
```

Whichever one you use, there are a few things to keep in mind:

```
i - insert mode
ESC - leave insert mode
yy - yank line (copy)
p - put line
dd - delete line
:w - write
:q - quite
:wq - write and quit
```

:::{.callout-note}
Vim -- Vi Improved -- is absolutely bonkers. It was made for programmers, by programmers, before the mouse became a thing. It will make you feel bad about yourself and question your abilities. If you want more info on what it can do, check out this link: https://docs.oracle.com/cd/E19455-01/806-2902/6jc3b36ee/index.html
:::

Once we are into the CRC, we are going to make a directory for our code:

```
mkdir model_predictions
```

Now we can navigate to it:

```
cd model_predictions
```

Now, let's take the following code:

```{python}
#| eval: false
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

work_data = pd.read_csv("/afs/crc.nd.edu/user/s/sberry5/model_predictions/level_up_data.csv")

y = work_data['separatedNY']

X = work_data['workDistance']

X = X.to_numpy()

X = X.reshape(-1, 1)

simple_logistic = LogisticRegression(solver="liblinear", random_state=1001)

simple_logistic.fit(X, y)

predicted_probs = simple_logistic.predict_proba(X)[:, 1]

pred_df = pd.DataFrame({"preds":predicted_probs})

pred_df.to_csv("/afs/crc.nd.edu/user/s/sberry5/model_predictions/model_predictions.csv")
```

```
/afs/crc.nd.edu/user/s/sberry5/model_predictions
```


And run:

```
touch make_predictions.py
```

And then:

```
vim make_predictions.py
```


Now we can go into paste mode:

```
ESC
:set paste
i
SHIFT + INS
```

You'll now be able to navigate over the file with `h`, `j`, `k`, and `l`.

For now, though, let's just write and quit that file:

```
:wq
```

We need to move our model into our directory now, which is where the program that we are using becomes helpful!

Finally, we need to use the appropriate path within our code!

Now we can deal with getting python going! 

We have some libraries to install:

```
module load python

pip3 install --user imblearn pandas scikit-learn joblib
```

The hard work is done, so now we can create a bash script to submit our job!

We will touch a file:

```
touch prediction_job.script
```

And paste in the following:

```
#!/bin/bash
#$ -M sberry5@nd.edu    # Email address for job notification
#$ -m abe               # Send mail when job begins, ends and aborts
#$ -q long              # Specify queue
#$ -pe smp 1            # Specify number of cores to use.
#$ -N predictions       # Specify job name

module load python

python3 make_predictions.py
```

Now, we can submit our job:

```
qsub prediction_job.script
```

## Retrieving Results

You can use either of the programs to transfer files back to your local machine. 

If you're on a Mac or Linux machine, you can just use `scp` on your local machine:

```
scp sberry5@crcfe02.crc.nd.edu:/afs/crc.nd.edu/user/s/sberry5/model_predictions/model_predictions.csv Documents/
```