---
title: "Travel the World with Homework 2"
author: "Your Name Here"
format:
  html:
    toc: true
    toc-location: left
    self-contained: true
jupyter: python3
---

Traveling the world is fun! You will use a few different resources to help you decide some exciting destinations to visit. 

## General Tips

This is very much a step-by-step process. Don't go crazy trying to get everything done with as few lines as possible. Read the documentation for the AlphaVantage api! Carefully explore all html pages. There isn't a need to get too fancy with anything here -- just go with simple functions and all should be good. **Don't print comments**, but use normal text for explanations.

## Step 1

```{python}

import glob as glob
import pandas as pd

files=glob.glob("/Users/totoh/Desktop/Unstructured Data/homework2/country_info/*.txt")

data = []
for file in files:
    with open(file, 'r') as f:
        parts = file.split('/')[-1].replace('.txt', '').split('_')
        data.append({
            'country': parts[0],
            'info_type': parts[1],
            'content': f.read()
        })

df = pd.DataFrame(data)
df


```

## Step 2

Use the CIA's World Factbook **country travel sheets** to produce a data frame with every country's name, major languages, driving direction, cuisine, and one other feature of your choosing. The Factbook is available here: https://www.cia.gov/the-world-factbook/

```{python}
import requests
from bs4 import BeautifulSoup
import time
import numpy as np
import pandas as pd

link = "https://web.archive.org/web/20260203121052/https://www.cia.gov/the-world-factbook/countries/"

response = requests.get(link)
soup = BeautifulSoup(response.content, 'html.parser')

sitemap = requests.get('https://web.archive.org/web/20260203121052/https://www.cia.gov/the-world-factbook/sitemap/sitemap-0.xml')
sitemap_soup = BeautifulSoup(sitemap.text, 'xml')

all_urls = [loc.get_text() for loc in sitemap_soup.select('loc')]
country_urls = [url for url in all_urls if '/countries/' in url and '/travel-facts/' in url]

json_links = ['https://web.archive.org/web/20260203121052/' + country_urls[i].replace('/countries/', '/page-data/countries/').replace('/travel-facts/', '/travel-facts/page-data.json') for i in range(len(country_urls))]

travel_list = []

for url in json_links:
    try:
        response = requests.get(url)
        data = response.json()['result']['data']['travelFact']

        country = data['placeName']
        values = data['values']

        lang = ''
        driving = ''
        cuisine = ''
        religion = ''

        for item in values:
            if item['attribute'] == 'majorLanguages':
                language = item['value']
            if item['attribute'] == 'roadDrivingSide':
                driving = item['value']
            if item['attribute'] == 'traditionalCuisine':
                cuisine = item['value']
            if item['attribute'] == 'religions':
                religion = item['value']

        travel_list.append([country, language, driving, cuisine, religion])

    except:
        continue


travel_pd = pd.DataFrame(travel_list, columns=['country', 'languages', 'driving_side', 'cuisine', 'religion'])

travel_pd['driving_side'] = travel_pd['driving_side'].str.replace('<.*?>', '', regex=True)
travel_pd['cuisine'] = travel_pd['cuisine'].str.replace('<.*?>', '', regex=True)
travel_pd['languages'] = travel_pd['languages'].str.replace('<.*?>', '', regex=True)
travel_pd['religion'] = travel_pd['religion'].str.replace('<.*?>', '', regex=True)

travel_pd




```

## Step 3

We want just the right amount of adventure to our travel, so use the State Department's **Travel Advisories** page to get a data frame with every country's name and travel advisory level. The travel advisories are available here: https://travel.state.gov/en/international-travel/travel-advisories.html. What are the most common Risk Indicators? What patterns do you see in terms of countries with high travel advisory levels?
```{python}
import requests
from bs4 import BeautifulSoup
import time
import numpy as np
import pandas as pd

link = "https://travel.state.gov/en/international-travel/travel-advisories.html"

response = requests.get(link)
soup = BeautifulSoup(response.content, 'html.parser')
table = soup.find("table")
tbody=table.find("tbody")
rows=tbody.find_all("tr")

data = []

for row in rows:
    try:
        destination = row.find("th").get_text
        level = row.find("td").get_text

        cells = row.find_all("td")
        risk_cell = cells[1]
        risk_spans = risk_cell.find_all("span")
        risks = [r.get_text(strip=True) for r in risk_spans]
        risk_text = ", ".join(risks)

        data.append([destination, level, risk_text])

    except:
        continue

df_advisory = pd.DataFrame(
    data,
    columns=["country", "level", "risk_indicators"]
)

df_advisory

risk_split = df_advisory["risk_indicators"].str.split(", ")
risk_exploded = risk_split.explode()
risk_counts = risk_exploded.value_counts()
risk_counts

#Crime is the most frequently listed risk indicator across countries

high_risk_df = df_advisory[
    df_advisory["level"].str.contains("Level 3|Level 4")
]

high_risk_df["risk_list"] = high_risk_df["risk_indicators"].str.findall(
    r"[A-Z\s]+(?=\s*\()"
)

high_risk_df

#The main patterns are that unrest appears very frequently, terrorism is also common, and many of the highest advisory countries are clustered in the Middle East.





```


## Step 4

Use the AlphaVantage api (FX_Daily at https://www.alphavantage.co/documentation/) to get daily exchange rates for the US and 3 other countries of your choosing. You cannot use any AlphaVantage packages (i.e., you can only use requests to grab the data). Tell me about the general trend that you are seeing. I don't care which viz package you use (e.g., seaborn, plotnine, plotly).

```{python}
import requests
import time
import pandas as pd

currencies = ['JPY', 'CNY', 'CHF']

fx_list = []

for currency in currencies:
    
    time.sleep(15)  
    
    url = f'https://www.alphavantage.co/query?function=FX_DAILY&from_symbol=USD&to_symbol={currency}&outputsize=full&apikey=YOUR_API_KEY'
    
    response = requests.get(url)
    data = response.json()
    
    ts = data['Time Series FX (Daily)']
    
    for date in ts:
        close_price = float(ts[date]['4. close'])
        fx_list.append([date, currency, close_price])

fx_df = pd.DataFrame(fx_list, columns=['date', 'currency', 'close'])


fx_df['date'] = pd.to_datetime(fx_df['date'])


fx_df = fx_df.sort_values('date')

fx_df
```

```{python}
import matplotlib.pyplot as plt

jpy = fx_df[fx_df["currency"] == "JPY"]

plt.figure()
plt.plot(jpy["date"], jpy["close"])
plt.show()
```

```{python}
jpy = fx_df[fx_df["currency"] == "CNY"]

plt.figure()
plt.plot(jpy["date"], jpy["close"])
plt.show()
```

```{python}
jpy = fx_df[fx_df["currency"] == "CHF"]

plt.figure()
plt.plot(jpy["date"], jpy["close"])
plt.show()
```


## Step 5

With all of this work out of the way, we can start getting down to strategy. Based upon the data that you've collected, what countries would you recommend visiting and why?
```{python}
#In recent years, the dollar has strengthened significantly against the Japanese yen, making Japan more affordable for American travelers, and since Japan also has a low travel advisory level, it offers the best overall value when considering both exchange rates and safety
```
