---
title: "Regular Expressions"
format:
  html:
    code-fold: true
jupyter: python3
---

## Symbols

- `.`:
- `^`:
- `$`:
- `[]`:
- `[^]`:
- `|`:
- `()`:
- `*`:
- `+`:
- `?`:
- `{n}`:
- `{n,}`:
- `{n,m}`:
- `\`:
- `\d`:
- `\D`:
- `\w`:
- `\W`:
- `\s`:
- `\S`:

### Posix Classes

- `[:alnum:]`: 
- `[:alpha:]`: 
- `[:digit:]`: 
- `[:lower:]`: 
- `[:upper:]`: 
- `[:punct:]`: 
- `[:space:]`: 


### Lookarounds

- `(?=)`: Positive lookahead
- `(?!)`: Negative lookahead
- `(?<=)`: Positive lookbehind
- `(?<!)`: Negative lookbehind


## Functions

### re

```{python}
#| eval: false
import re

string = '''
Lil Baby helped you get your lingo up (What?)
21 gave you false street cred
Thug made you feel like you a slime in your head (Ayy, what?)
Quavo said you can be from Northside (What?)
2 Chainz say you good, but he lied
'''

re.findall('\d+', string)

re.sub(r'\d+', 'X', string)

re.split(r'\d+', string)

re.match(r'\d+', string)
```

#### On the use of r

You will often see the letter `r` before the string in regular expressions. This is to denote a raw string. This is important because it tells Python to ignore any special characters in the string. For example, if you want to match a backslash, you would need to use `\\` in a regular string. However, in a raw string, you can use `\`. 

### pandas

```{python}
import pandas as pd

example_df = pd.DataFrame(
    {'text': [string]}
)

example_df['text'].str.findall(r'\d+')

example_df['text'].str.replace(r'\d+', 'X')

example_df['text'].str.split(r'\d+')

example_df['text'].str.match(r'\d+')

example_df['text'].str.extract(r'(\d+)')

example_df['text'].str.extractall(r'(\d+)')

example_df['text'].str.contains(r'\d+')

example_df['text'].str.count(r'\d+')
```


```{python}
import pandas as pd
import pyarrow as pa
import re
```

```{python}
test_strings = [
    "You've been dreaming ofThe fate of Ophelia",
    "[Chorus] I wave goodbye to the end of beginning [verse 1]",
    " Oh-oh-oh, I'm done hidin',  now I'm shinin' like I'm born to be ",
    "I don't even know what she said But this what I hear in my head Embedded lyrics here", 
    "https://www.billboard.com/charts/hot-100/2025-01-11/"
]
```

```{python}
lyrics_df = pd.DataFrame(
    {"lyrics": test_strings}
)

lyrics_df['lyrics']
```

## Examples

### Removing Specific Words

We can remove "Embedded" and everything that follows it in the 4th string.

```{python}
lyrics_df['lyrics'].str.replace(r'', '', regex=True)[3]
```

### Removing Extra Space

We'll want to replace multiple spaces and leading/trailing spaces with a single space.

```{python}
lyrics_df['lyrics'].str.replace(r'', ' ', regex=True)[2]
```

### Removing Bracketed Text

To remove bracketed text from the 2nd string, we need to be careful!

```{python}
lyrics_df['lyrics'].str.replace(r'', '', regex=True)[1]
```

### Splitting Text

Likely the biggest time saver in the world!

```{python}
lyrics_df['lyrics'].str.replace('', '', regex=True)[0]
```

### Extracting Text
Let's pull the year out of the URL.
https://www.billboard.com/charts/hot-100/2025-01-11/
```{python}
lyrics_df['lyrics'].str.extract('')
```

And the genre:

```{python}
re.search("",lyrics_df['lyrics'][4]).group(0)
```

```{python}
lyrics_df.apply(lambda x: re.search("(?<=charts/).*(?=/\d{4})",x['lyrics']).group(0), axis=1)
```

## More Work

```{python}
all_lyrics = pd.read_feather(
    '/Users/sberry5/Documents/teaching/UDA/code/lyrics_scrape_python/complete_lyrics_2025.feather', 
    dtype_backend='pyarrow'
)
```